# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: sonicbld

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60

    pool:
      vmImage: ubuntu-20.04

    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-buster:latest

    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: build
        pipeline: 9
        artifact: sonic-swss-common
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/master'
      displayName: "Download sonic swss common deb packages"

    - script: |
        set -ex

        #install HIREDIS
        sudo apt-get install -y libhiredis0.14 libhiredis-dev

        # Install libnl3
        sudo apt-get install -qq -y \
            libnl-3-dev \
            libnl-genl-3-dev \
            libnl-route-3-dev \
            libnl-nf-3-dev

        #install libswsscommon
        sudo dpkg -i sonic-swsw-common/libswsscommon_1.0.0_amd64.deb
        sudo dpkg -i sonic-swss-common/libswsscommon-dev_1.0.0_amd64.deb

        ./autogen.sh

        dpkg-buildpackage -rfakeroot -us -uc -b -j$(nproc) && cp ../*.deb $(Build.ArtifactStagingDirectory)/
      displayName: "Build"

    - publish: $(Build.ArtifactStagingDirectory)/
      artifact: sonic-stp
      displayName: "Archive artifacts"
