# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: sonicbld

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job:
    pool: sonicbld
    displayName: "build"
    timeoutInMinutes: 60
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'
    - script: |
        echo Hello
        # the following is copied from jenkins
        # set -ex
        # ./scripts/common/sonic-stp-build/build.sh'
    - publish: $(System.DefaultWorkingDirectory)/target/
      artifact: sonic-stp
      displayName: "Archive artifacts"

